version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/st-payment-gateway
permissions:
  - object: /home/ubuntu/st-payment-gateway
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 6000
      runas: root

